### ISSUE TITLE
OneRoom을 구현하는 방향성

### ISSUE THREAD

**Issue by kimjunghwannn** [2024-Hansung-Capstone/ProjectJ-Backend#11]
제가 원룸을 구현하기 전에 원룸 open api들을 찾아 보았는데
![image](https://github.com/2024-Hansung-Capstone/ProjectJ-Backend/assets/157611169/8bb4fd20-bc24-441a-800e-a7d68f6f4583)
공공 데이터 포털에서 이 정도 제공을 하더라구요

가격이나 방에 대한 설명이 없어 유용한 데이터는 아니라고 생각이 들어서 든 생각인데 
api사용이 아닌 중고물품처럼 사용자 간에 사고 파는 방식으로 하는게 좋을거 같다는 생각이 들었습니다.

수진님 생각은 어떠신가요?

**Comment by kimjunghwannn** [comment]
게시판들이 개성없이 일정해진다는 의견에 동의합니다.
수진님 의견은
![image](https://github.com/2024-Hansung-Capstone/ProjectJ-Backend/assets/157611169/f2abe58e-9b40-43ad-b246-013c99c0d052)
이렇게 지도에다가 제가 구한 원룸 정보를 나타내는 방식을 말씀하시는 거죠?

국토교통부 단독/다가구 전월세 openapi인데 
<갱신요구권사용> </갱신요구권사용>
<건축년도>1993</건축년도>
<계약구분>신규</계약구분>
<계약기간>22.03~24.03</계약기간>
<계약면적>61.61</계약면적>
<년>2022</년>
<법정동> 청운동</법정동>
<보증금액> 34,000</보증금액>
<월>1</월>
<월세금액> 10</월세금액>
<일>8</일>
<종전계약보증금> 0</종전계약보증금>
<종전계약월세> 0</종전계약월세>
<지역코드>11110</지역코드>
이런 정보를 제공하는 api입니다.
이 openapi를 사용하여 구현하려고 하는데 어떤가요?

**Comment by ssarisong** [comment]
@kimjunghwannn 
넵 써주신 내용이 제가 생각한 방식이 맞습니다. 프론트에서 작업한 부분도 확인해보았을 때 지도에 표시할 준비를 하기 위해 지도 api를 사용한 것으로 보여집니다.

저희가 사용해야할 데이터는 제가 보기엔 원룸의 어떤 정보가 있나 보다는 원룸의 적당한 정보만 있으면 그 정보와 함께 지도에 찍을 수 있는 정확한 위치 지점을 전달하는것이 가장 중요한 목표일것이라 보이는데 X, Y 좌표값이 안나와있는점이 조금 아쉽습니다ㅠㅠ

만약 좌표가 아니라도 전체 주소를 받아올 방법이 있다면 지오코딩이라는 기법을 사용하여 좌표로 변환하는 작업을 통해 위치 정보를 넘겨줄 수 있을 것 같습니다.

https://www.vworld.kr/dev/v4dv_geocoderguide2_s001.do
위 링크는 지오코딩을 할 수 있게 해주는 API 링크입니다. 만약 지오코딩을 활용하신다면 좌표계는 WGS-84(EPSG:4326)를 사용하여서 추출해주시면 될 것 같습니다.

**Comment by kimjunghwannn** [comment]
국토교통부 연립다세대 전월세api에는 응답 메시지에 지번이 있어서 주소를 받아올 수는 있네요
<갱신요구권사용>사용</갱신요구권사용>
<건축년도>2010</건축년도>
<계약구분>갱신</계약구분>
<계약기간>22.01~24.01</계약기간>
<년>2022</년>
<법정동> 청운동</법정동>
<보증금액> 42,000</보증금액>
<연립다세대>효산빌리지</연립다세대>
<월>1</월>
<월세금액> 0</월세금액>
<일>8</일>
<전용면적>65.59</전용면적>
<종전계약보증금> 40,000</종전계약보증금>
<종전계약월세> 0</종전계약월세>
<지번>52-5</지번>
<지역코드>11110</지역코드>
<층>2</층>
지번과 법정동 이용하면 주소를 찍어 올 수 있더라구요 이걸 통해서 한 번 해볼게요

**Comment by ssarisong** [comment]
@kimjunghwannn 
넵 몇개 테스트해서 포인트가 잘 찍히는지 위치 확인해서 봐주시면 감사드리겠습니다!
