### ISSUE TITLE
원룸을 지도에 나타나게 하는 api의 요청파라미터는 어떤게 좋을까요?

### ISSUE THREAD

**Issue by kimjunghwannn** [2024-Hansung-Capstone/ProjectJ-Backend#12]
원룸에서 지도를 통해서 매물들을 나타나게 할 때 요청파라미터를 startX,endX,startY,endY로 잡아서 이 범위안에 있는 x,y 원룸들을 나타나게 하려는데 이 방식 어떤가요?

**Comment by ssarisong** [comment]
@kimjunghwannn 
지도 API를 쓸 쪽이 프론트엔드팀이라 프론트엔드쪽에 물어봐서 지금 사용하고 있는 지도 API가 어떤 방식으로 좌표를 뿌려주면 사용하기 편할지 상의해보고 결정해주시면 될 것 같습니다.
