### ISSUE TITLE
원룸의 좌표를 지도에 띄우는 api 결과

### ISSUE THREAD

**Issue by kimjunghwannn** [2024-Hansung-Capstone/ProjectJ-Backend#13]
![image](https://github.com/2024-Hansung-Capstone/ProjectJ-Backend/assets/157611169/0d15f450-fdb9-4f0f-a9a2-8474f0893999)
위 사진은 종로구 원룸들의 주소로 알아낸 x,y좌표들 입니다.
위와 같이 좌표들이 많이 세분화 되어 있지 않고 어느정도 가까우면 좌표가 동일하네요.
이정도 좌표도 괜찮을까요?

**Comment by ssarisong** [comment]
@kimjunghwannn 
사진으로 확인했을 때 일단 이 결과값이 원룸의 상세주소를 넣고 그 원룸의 좌표인 것인지 아니면 앞의 행정동 좌표인 것인 지 한번 더 알려주시면 좋겠습니다.

그리고 혹시 지오코딩을 했을 때 소수점으로 값이 나오진 않으신가요? 우리나라가 특히 작아서 대부분이 x좌표 127번대에 y좌표 30중후반대일거라 소수점 한 10째자리정도까지는 나오는 것으로 알고 있어서요.

마지막으로 원룸의 주소는 상세주소까지 잘 확인이 되는지 알려주시면 감사드리겠습니다.

**Comment by kimjunghwannn** [comment]
1. 지오코더 요청파라미터가 행정동 + 지번이므로 원룸의 좌표입니다
2. 아 제가 그 점을 놓쳤네요. 자료형을 변환해서 해보겠습니다.
3. 원룸은 상세주소까지는 지원 해주지 않더라구요 그리고 심지어 이름도 잘 나오지 않는 곳도 많습니다.
