### ISSUE TITLE
포인트 구현 계획

### ISSUE THREAD

**Issue by kimjunghwannn** [2024-Hansung-Capstone/ProjectJ-Backend#15]
User:
-entity: 포인트 값, 포인트 값에 따른 계급(예: 포인트 1부터 1000까지는 자취 어린이, 1001부터 2000까지는 자취 중학생,... 등등), 출석체크한 날짜 값 Column 추가
-service: 로그인 기능 부분(getAccessToken)에 오늘 날짜를 통해 출석체크하여 출석체크 하루당 10포인트 지급,
포인트를 획득시 사용하는 서비스api로 특정계급 도달 포인트 획득시 그 특정 계급으로 올려주는 api

Board:
-service: 사용자가 댓글, 게시글 작성시 댓글 1포인트, 게시글 5포인트 지급 댓글과 게시글에 좋아요를 받으면 좋아요당 5포인트 지급

**Comment by ssarisong** [comment]
포인트 쪽으로 Entity와 기본 Service 생성 완료되면, 작성해주신 대로 User 쪽 기능 추가해보겠습니다. 기본적인 포인트 올리는 Service부터 만들어주시고 완성되면 알려주시면 감사하겠습니다.
