### ISSUE TITLE
보드 구현중 알림부분 오류

### ISSUE THREAD

**Issue by kimjunghwannn** [2024-Hansung-Capstone/ProjectJ-Backend#17]
"message": "Cannot delete or update a parent row: a foreign key constraint fails (`projectj`.`notification`, CONSTRAINT `FK_e8fc34e5036ba2e4f1220ed0a62` FOREIGN KEY (`likeId`) REFERENCES `like_user_record` (`id`))",
like_user_record삭제 할 때 이렇게 떴어요

@ManyToOne(() => LikeUserRecord, { cascade: true, nullable: true })
  @JoinColumn()
  @Field(() => LikeUserRecord, {
    nullable: true,
   ###  ***onDelete: 'CASCADE',***
    description: '알림이 생성된 중고 상품 정보',
  })
  like?: LikeUserRecord;

이게 onDelete: 'CASCADE' 들어가야 할거 같습니다

그리고 board에서 게시글 작성시 +10이 들어오지만 그 작성자가 그 게시물을 다시 삭제한다면 다시 -10이 되게 하는 것으로 구현하였습니다.(댓글, 좋아요도 동일)

**Comment by ssarisong** [comment]
아 알림이 생성된 상태에서 게시글을 삭제하려면 오류가 나겠네요. 확인해주셔서 감사합니다!
그럼 수정해놓겠습니다.
