### ISSUE TITLE
오류로 인한 User부분 수정 

### ISSUE THREAD

**Issue by kimjunghwannn** [2024-Hansung-Capstone/ProjectJ-Backend#4]
backend-1   | [Nest] 52  - 02/14/2024, 4:40:41 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the UserService (UserRepository, ?, JwtService). Please make sure that the argument TokenRepository at index [1] is available in the UserModule context. 
UserService가 TokenRepository에 대한 의존성을 해결할 수 없다는 문제가 있어서 User부분을 수정했습니다.

![image](https://github.com/2024-Hansung-Capstone/ProjectJ-Backend/assets/157611169/912102c2-16ca-4d42-ad31-e6219c1131a1)
UserModule

![image](https://github.com/2024-Hansung-Capstone/ProjectJ-Backend/assets/157611169/5ef02362-2a2f-4b4d-8fa2-b9de9f7e8a41)
User의 구조

![image](https://github.com/2024-Hansung-Capstone/ProjectJ-Backend/assets/157611169/5e79aced-1041-461a-b850-2a989028f512)
token.repository.ts

![image](https://github.com/2024-Hansung-Capstone/ProjectJ-Backend/assets/157611169/c15ed089-67f0-42ab-91a0-d7a98b18e204)
user.repository.ts 

이렇게 수정하니 오류가 해결되었습니다. 보시고 수정할 부분 없으면 이대로 push 하겠습니다

**Comment by ssarisong** [comment]
확인했습니다.

현재 샘플로 공유드린 User API들은 불안정할 수 있습니다.

지금은 USER쪽 API들은 거의 구현이 되어가기 때문에 지금까지 한 부분들 이제 1차적으로 합쳐보려고 합니다.

그래서 User쪽에서 수정하신 부분들은 롤백해주시고 우선 제쪽에서 만든 User브랜치와 합친 후에도 같은 에러가 나면 그때 수정하는 방향으로 하는게 좋을 것 같습니다!
