### ISSUE TITLE
Used_products 테스트 결과 

### ISSUE THREAD

**Issue by kimjunghwannn** [2024-Hansung-Capstone/ProjectJ-Backend#6]
![image](https://github.com/2024-Hansung-Capstone/ProjectJ-Backend/assets/157611169/ffda8c8e-07d6-4779-8f5d-8a655dbd38fb)
usedProductByuser_Id부분

![image](https://github.com/2024-Hansung-Capstone/ProjectJ-Backend/assets/157611169/a68cbd21-b94f-4ad7-83a5-221eb5c86673)
Context를 사용해서 유저를 가져오는 부분들 User에 리졸버도 그렇고 제가 만든 UsedProduct도 그렇고 일단 Usedguard데코레이터 사용하는 것들은 다 저렇게 허가 되지 않았다고 하네요 

이거 두 오류들 방법 아시면 말씀 부탁드립니다

나머지 부분들은 잘 됩니다 (addViewToPost,usedProducts,usedProductById,getPosts)

**Comment by ssarisong** [comment]
## 수정 결과
![image](https://github.com/2024-Hansung-Capstone/ProjectJ-Backend/assets/107747359/5133382b-dab6-4284-9c45-cfbf23d56ed2)

우선 해당 내용 수정하여 커밋하였습니다.

repository에서 조회, 수정을 거칠 때는 await로 작업이 완료될 때 까지 기다려주는 것이 좋습니다.

추가적인 내용은 service의 findByuser_Id에서 수정한 내용과 가장 최근 커밋의 변경사항들 확인해주시면 될 것 같습니다.

그리고 Context를 통해 현재 로그인된 사용자의 id를 가져올 때에는 Resolver 내에서 context.req.user.id로 직접 가져와서 service에 전달하시면 될 것 같습니다.

마지막으로 user관련 조회를 하실 때 userSerivce를 불러와서 그 안에 있는 기능들을 우선적으로 사용해 주시고, 없는 기능은 저에게 얘기해주시면 추가하도록 하겠습니다.

현재 수정사항 참고하여 지금까지 구현해주신 내용들 수정하여 다시 커밋해주시면 감사드리겠습니다.
