### ISSUE TITLE
Used_product 2차 테스트 결과

### ISSUE THREAD

**Issue by kimjunghwannn** [2024-Hansung-Capstone/ProjectJ-Backend#7]
![image](https://github.com/2024-Hansung-Capstone/ProjectJ-Backend/assets/157611169/9c6f596c-a212-467c-ae8d-7e5e5f16c1e6)
현재 로그인 한 유저와 게시글에 저장된 유저의 정보를  비교하여 삭제,업데이트 하는 부분에 이런 오류가 발생하고 있습니다.

async update(
    id: string,
    usedProduct: UpdateUsedProductInput,
    user_id: string,
  ): Promise<Used_product> {
    const used_product = await this.findById(id);
    const { title, price, detail, category, state } = usedProduct;
    if (!used_product) {
      throw new NotFoundException(`Id가 ${id}인 것을 찾을 수 없습니다.`);
    }
    const user = await this.userService.findById(user_id);
    const now_user = await this.userService.findById(used_product.user.id);
    if (now_user.id !== user.id) {
      throw new ForbiddenException(
        `본인이 작성한 게시글만 수정할 수 있습니다.`,
      );
    }
    used_product.title = title;
    used_product.price = price;
    used_product.detail = detail;
    used_product.category = category;
    used_product.state = state;
    await this.usedProductRepository.save(used_product);
    return await this.usedProductRepository.findOne({ where: { id: id } });
  }

 const now_user = await this.userService.findById(used_product.user.id);
    if (now_user.id !== user.id) {
 **이 부분에서 오류가 발생하고 있고 제가 쓰고있는 now_user를 가져오는 방식이 잘못된거 같은데 제 생각은 User의 entity에 Used_product와의 관계를 적어서 return await this.userRepository.find({
      where: { used_product: { id: used_products.id } }, 이렇게 now_user를 가져와서 하는 방식을 생각하고 있습니다**

이런 오류 말고는 다른 것들은 모두 정상 작동합니다

**Comment by ssarisong** [comment]
update() 기능에서 맨 첫번째 줄 `const used_product = await this.findById(id);`로부터 오류가 시작되는 것으로 보입니다.

현재 findByuser_id() 에서는 relations를 설정하여 user안의 id값을 가져올 수 있게 되어있지만 findById는 relations가 설정되어 있지 않아서 user 엔티티와 연결되지 못하여 id값을 찾지 못해 undefined 에러가 뜨고 있습니다.

findById()의 내용을 아래와 같이 수정하면 오류가 해결되지 않을까 생각됩니다.
`return await this.usedProductRepository.findOne({where: { id: id }, relations: ['user']});`
